-- RxScan Supabase setup
-- Run this in the Supabase SQL Editor.

begin;

create table if not exists public.medications (
  id bigint generated by default as identity primary key,
  name text not null,
  generic text default '',
  barcode text not null unique,
  category text not null default 'Other',
  price_box numeric(10,2) not null default 0,
  units_per_box integer not null default 1,
  stock integer not null default 0,
  reorder integer not null default 10,
  zone text not null default '',
  shelf text not null default '',
  expiry date,
  mfr text default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists medications_set_updated_at on public.medications;

create trigger medications_set_updated_at
before update on public.medications
for each row
execute function public.set_updated_at();

alter table public.medications enable row level security;

drop policy if exists "Authenticated staff can read medications" on public.medications;
create policy "Authenticated staff can read medications"
on public.medications
for select
to authenticated
using (true);

drop policy if exists "Authenticated staff can insert medications" on public.medications;
create policy "Authenticated staff can insert medications"
on public.medications
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated staff can update medications" on public.medications;
create policy "Authenticated staff can update medications"
on public.medications
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated staff can delete medications" on public.medications;
create policy "Authenticated staff can delete medications"
on public.medications
for delete
to authenticated
using (true);

insert into public.medications (
  name, generic, barcode, category, price_box, units_per_box, stock, reorder, zone, shelf, expiry, mfr
)
values
  ('Amoxil', 'Amoxicillin', '3400936345507', 'Antibiotics', 12.50, 21, 45, 10, 'A — Antibiotics', 'A1-L2', '2026-08-15', 'GSK'),
  ('Doliprane', 'Paracetamol', '3400935851218', 'Analgesics', 2.80, 16, 120, 30, 'B — Pain Relief', 'B3-L1', '2027-03-20', 'Sanofi'),
  ('Kardegic', 'Aspirin 75mg', '3400936123456', 'Cardiovascular', 6.20, 30, 8, 15, 'C — Cardio', 'C2-L3', '2025-12-01', 'Sanofi'),
  ('Metformine', 'Metformin 850mg', '3400937654321', 'Diabetes', 4.10, 30, 0, 20, 'D — Diabetes', 'D1-L2', '2026-06-30', 'Biogaran'),
  ('Ventoline', 'Salbutamol', '3400934567890', 'Respiratory', 7.90, 1, 28, 8, 'H — Respiratory', 'H1-L1', '2026-09-15', 'GSK'),
  ('Atorvastatine', 'Atorvastatin 20mg', '3400930012345', 'Cardiovascular', 16.40, 30, 5, 10, 'C — Cardio', 'C1-L2', '2026-11-20', 'Pfizer'),
  ('Omeprazole', 'Omeprazole 20mg', '3400935098765', 'Gastrointestinal', 3.60, 28, 62, 15, 'B — Pain Relief', 'B2-L1', '2027-01-10', 'Mylan'),
  ('Vitamine D3', 'Cholecalciferol 2000UI', '3400931122334', 'Vitamins & Supplements', 5.20, 60, 88, 20, 'E — Vitamins', 'E1-L1', '2026-05-15', 'Lescuyer'),
  ('Augmentin', 'Amoxicillin+Clavulanate', '3400932233445', 'Antibiotics', 18.90, 12, 3, 8, 'A — Antibiotics', 'A2-L1', '2025-11-30', 'GSK'),
  ('Bisoprolol', 'Bisoprolol 5mg', '3400933344556', 'Cardiovascular', 9.30, 30, 34, 10, 'C — Cardio', 'C3-L2', '2026-07-18', 'Teva'),
  ('Fluoxetine', 'Fluoxetine 20mg', '3400934455667', 'Neurology', 11.50, 28, 18, 5, 'B — Pain Relief', 'B4-L3', '2026-10-22', 'Eli Lilly'),
  ('Cetirizine', 'Cetirizine 10mg', '3400935566778', 'Respiratory', 3.90, 7, 71, 15, 'H — Respiratory', 'H2-L2', '2027-02-28', 'Zentiva'),
  ('Insuline Glargine', 'Insulin Glargine', '3400936677889', 'Diabetes', 48.70, 5, 12, 4, 'F — Refrigerated', 'F1-L1', '2026-04-10', 'Sanofi'),
  ('Hydrocortisone 1%', 'Hydrocortisone', '3400937788990', 'Dermatology', 4.80, 1, 22, 6, 'G — Dermatology', 'G1-L1', '2026-12-15', 'Biogaran'),
  ('Levothyrox', 'Levothyroxine 50mcg', '3400938899001', 'Hormones', 5.50, 30, 41, 10, 'D — Diabetes', 'D2-L1', '2026-08-30', 'Merck')
on conflict (barcode) do nothing;

commit;
